### ISSUE TITLE
migration-script.sh should be executable

### ISSUE THREAD

**Issue by robandpdx** [github/gh-gei#671] opened 2022-10-07 00:44 UTC
## Description

After running `gh gei generate-script...` the resulting script is not executable, resulting in customer frustration and a bad experience.

## Reproduction Steps

Run `gh gei generate-script...`, the `ls -l migration-script.sh`, Notice the permission.

**Comment by dylan-smith** [comment] 2022-10-19 21:31
duplicate of #305

**Closed by dylan-smith** 2022-10-19 21:31 UTC
Labels: bug
