### ISSUE TITLE
Powershell error running generated migration script. Switch-Process Line 19 error, Command '' was not found. The specified command must be an executable.

### ISSUE THREAD

**Issue by robandpdx** [github/gh-gei#739] opened 2022-11-16 17:24 UTC
## Description

Using pwsh 7.3.0 on mac, I am seeing the following error when running the script generated via `generate-script` command...  

```
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
Switch-Process: /Users/robandpdx/github/gei-demo/migration-script.ps1:19
Line |
  19 |      $MigrationID = Exec $ScriptBlock | ForEach-Object {
     |                     ~~~~~~~~~~~~~~~~~
     | Command '' was not found. The specified command must be an executable.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.

function ExecAndGetMigrationID {

  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
Required argument missing for option: '--migration-id'.

Description:
  Waits for migration(s) to finish and reports all in progress and queued ones.
  Note: Expects GH_PAT env variable or -- option to be set.

Usage:
  gh-gei wait-for-migration [options]

Options:
  --migration-id <migration-id> (REQUIRED)  Waits for the specified migration to finish.
  --github-target-pat <github-target-pat>
  --verbose
  -?, -h, --help                            Show help and usage information


[10:38 AM] [INFO] You are running the latest version of the gei CLI [v0.31]
[10:38 AM] [ERROR] GH_PAT environment variable is not set.
=============== Summary ===============
Total number of successful migrations: 7
Total number of failed migrations: 0
```

## Reproduction Steps
1. Install powershell 7.3.0 on mac via the command...  
`brew install --cask powershell`
Or if you already have a version of powershell installed run...  
`brew reinstall --cask powershell`

2. Use gh gei to generate a migration script.  
3. Run the script.  
4. Observe the errors.  

## Workaround
Downgrading powershell to 7.2.6 seems to make the issue go away.  
1. Uninstall powershell 7.3.0...
`brew uninstall --cask powershell`
2. Download the package from the [PowerShell v7.2.6 release assets](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.6). For me this is [powershell-lts-7.2.6-osx-arm64.pkg](https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-lts-7.2.6-osx-arm64.pkg).  
3. Install powershell 7.2.6 package from the command line...
`sudo installer -pkg ~/Downloads/powershell-lts-7.2.6-osx-arm64.pkg -target /`
4. Confirm that powershell 7.2.6 is installed...
`pwsh --version`  
5. Profit!

**Comment by robandpdx** [comment] 2022-11-16 18:12
I found these, which might be of interest...
https://github.com/PowerShell/PowerShell/issues/18568
https://github.com/PowerShell/PowerShell/issues/18554

**Comment by timrogers** [comment] 2022-12-15 16:37
Another customer has reached out to me today with this problem. I advised them to downgrade their PowerShell.

**Comment by dylan-smith** [comment] 2023-01-12 20:52
We've been trying to reproduce this without success. Tried on powershell 7.3.0 and 7.3.1 (the latest) on windows, and 7.3.1 on a mac. Even had @robandpdx try it again on his machine and it worked.

I don't doubt there is a problem somewhere that needs to be fixed, but until we can repro it I'm going to close this issue as there's not much else we can do.

If somebody runs into this again please re-open this issue.

PS - The workaround I had planned to attempt if I could repro it would be to add this line to the generated script:
`$PSNativeCommandArgumentPassing = "Legacy"`

**Closed by dylan-smith** 2023-01-12 20:52 UTC
Labels: bug

**Comment by timrogers** [comment] 2023-01-13 12:29
I just tried to reproduce this myself with a fresh Powershell 7.3.1 installation, just to get a third pair of eyes, and I can't reproduce it.

As @dylan-smith said, if anyone can reproduce this, please do re-open the issue ❤️
