### ISSUE TITLE
Retry integration test setup on failure

### ISSUE THREAD

**Issue by dylan-smith** [github/gh-gei#659] opened 2022-09-23 19:01 UTC
The general process of our integration tests is:
1. Reset test environment (delete all the things)
2. Create sample testing data
3. Run migrations
4. Assert resulting state

We already added retries if it fails during step 1 (#634 ) but if it fails during Step 2 (like it did here: https://github.com/github/gh-gei/actions/runs/3114726847/jobs/5050886124#step:14:562) the test will fail.

If it fails during creating the test data, we should reset the test environment and start over.

**Comment by timrogers** [comment] 2022-11-04 15:10
@dylan-smith Is this a dupe of #635?

**Comment by dylan-smith** [comment] 2022-11-06 04:28
> @dylan-smith Is this a dupe of #635?

yes, I closed the other issue in favor of this one.

**Closed** 2022-11-10 06:02 UTC
Labels: task
