### ISSUE TITLE
Failure to migrate PRs during GH → GH migration even after stripping contemporarily invalid blob

### ISSUE THREAD

**Issue by danyalaytekin** [github/gh-gei#778] opened 2023-01-12 07:36 UTC
## Summary

A repository which contains a blob which has become invalid for GitHub during the repository's lifetime does not appear to be a candidate for retention of PR history during a GitHub → GitHub migration, even after revising its history to remove the blob.  

Theory: Closed pull requests depend on `/refs/pull` references, whose pushes are not accepted after they are revised, meaning that the old tree containing the now-invalid blob continues to live on in GitHub.

If true, the implication is that a customer will be limited to their current GitHub instance indefinitely, unable to move even to another GitHub instance.  Arguably an exception should be made to allow such a 'legacy repository' to be transferred, and such an exception would not set a precedent of breaking the rules around repository limits, since nothing is being "created" and the migration does not involve a non-GitHub service.

## Description

I'm helping to migrate a repository from GHES to GHEC.  The repo was created in 2011 and has been hosted on GHES since that time.  Early in its lifetime, two blobs weighing over 100MB made it into the repo on GHES.  They were deleted in 2012.

Several attempts have been made to transfer this repository to GHEC using `gh gei`, with each ultimately failing.

### Attempt 1: straightforward migration attempt

As expected, this attempt failed because of the presence of the two large files in the tree.

```
MigrateRepositoryJob: File <filename> is <size>; this exceeds GitHub's file size limit of 100.00 MB
```

### Attempt 2: rewrite repo with `git filter-repo`, before trying migration again

First, the large files were removed using the following process, and the repo overwritten on GHES:

```bash
brew install git-filter-repo
git clone --mirror git@server:org/repo.git
pushd repo
git filter-repo --strip-blobs-bigger-than 100M
git push --force
popd
```

GHES accepted the push of all references except those beginning with `/refs/pull` which I've since learned are read-only/synthetic.  

This time, the result of the `gh gei` migration from GHES to GHEC was:

- commits, tags, and branches were transferred successfully
- `/refs/heads/master` and `/refs/pull/*` failed to transfer, with the error message shown below
- no pull requests were transferred

```
ERROR -- MigrateRepositoryJob: Refspec push likely failed due to being too large (> 2GB)
ERROR -- MigrateRepositoryJob: Refspecs in question: ["refs/heads/master", "refs/pull/1/head", ... , "refs/pull/29/head", "refs/pull/29/merge", ..., "refs/pull/97/head"]
```

It's possible that open pull requests would actually have been successfully transferred to GHEC, since the push of their branches to GHES had rewritten their history in a pleasant way. But their ids began with a number beyond the 100 entry threshold where the `gh gei` script gave up after during its run, according to the "Refspecs in question" array mentioned above, so I can't be sure.

## Reproduction Steps

1. Somehow smuggle a repository `R` into a GitHub instance `G1` that contains a rule-breaking blob `X` (in this issue's case, with a size greater than 100MB)
1. Rewrite `R` and observe effects:
    1. Create a pull request `P1` containing one commit `C1`, and merge it
    1. Create a pull request `P2` containing one commit `C2`, and close it without merging it
    1. Create a pull request `P3` containing one commit `C3` on a branch `B3`, and leave it open
    1. Strip `X` from the repo using a tool such as `git filter-repo`
        1. Observe locally that the following SHAs were revised:
            1. `C1` became `C1.new`
            1. `C2` became `C2.new`
            1. `C3` became `C3.new`
            1. Branch `B3` now points to `C3.new` instead of `C3`
    1. Force push back to `R` on `G1`:
        1. In the console log:
            1. Observe that `B3`'s push was accepted
            1. Observe that `/refs/pull/1/head`, `/refs/pull/2/head`, `/refs/pull/2/merge`, and `/refs/pull/3/head` were rejected
        1. In the browser:
            1. Observe `P3` has been revised so that `B3` now points to `C3.new`, the PR's target is the rewritten `master` branch and everything generally looks quite pleasant
            1. Observe that `P1` and `P2` still reference the old commits `C1` and `C2`
1. Attempt to migrate `R` from `G1` to another GitHub instance `G2` using `gh gei` and observe effects:
    1. Run the migration (in this issue's case, `G1` is GHES and `G2` is GHEC)
    1. Observe the error `ERROR -- MigrateRepositoryJob: Refspec push likely failed due to being too large (> 2GB)` and a list of synthetic references
    1. Observe that all commits, tags, and branches were migrated successfully to `G2`
    1. Observe that all* pull requests are missing 
  
\* As mentioned in the description it's possible that some _open_ pull requests will be transferred - I was unable to verify this in my own scenario because there were more than 100 references corresponding to closed PRs.

**Comment by timrogers** [comment] 2023-01-12 10:11
@danyalaytekin Thanks for submitting this issue, and for sharing detailed instructions on how to reproduce the issue. That is super helpful! 💖

We use this repo for issues with the open-source `gh gei` CLI which runs on your machine, but the problem you're reporting here is related to our backend logic which runs behind the scenes to perform a migration.

Because of that, I'm closing to close this issue - but it would be great if you could submit everything you shared above in a [GitHub Support ticket](https://support.github.com/?tags=dotcom-footer), and our engineering team will pick this up and investigate.

**Closed by timrogers** 2023-01-12 10:11 UTC
Labels: bug

**Comment by danyalaytekin** [comment] 2023-01-12 10:25
That makes sense, thanks @timrogers.  Will follow up there.  🙂

**Comment by robandpdx** [comment] 2023-01-12 14:47
@danyalaytekin The theory above is disproven. I have done LFS migrations on repos prior to using GEI to migrate from GHES to GHEC and the PRs migrate even though they now reference SHAs that no longer exist in the repo due to the history rewriting of the LFS migrations.

**Comment by danyalaytekin** [comment] 2023-01-12 15:21
Hi @robandpdx, thanks.  Thing is, I'm still able to navigate my way around the old tree(s) and visit URLs representing the problematic files, and commits referring to them, in GHES (migration source).  So those ghosts are still around.  Were you able to do that after your rewrite?  Support are looking into it now though so we're in safe hands.

**Comment by theamk** [comment] 2025-05-17 03:40
Update on this, for those who stumble upon this ticket. I was doing some migrations with large files, and spend many hours before finally solving this

- The moment you've merged a single PR contains large files (in PR or in base commit), you can no longer fix it easily. We tried LFS migration on our test repo, and all this means is that we've got double the refs - all the heads, tags etc were pointing to post-LFS versions, but `pull/1/head` refs were still there, and no amount of git pushing could fix this, migration was failing as before. Git LFS 
    - This means @robandpdx 's comment is only true if you didn't merge any PRs with either large files, or which were based on branches with large files.
    - while writing the comment, I've discovered this manual page: [removing-sensitive-data-from-a-repository](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository). It confirms this point: if you want to permanently delete data (be it to remove secrets, or to move commits to LFS), you start by rewriting the repository *and then asking support to "dereference or delete any affected PRs"*
- When we contacted github support we eventually were given admin commands for github enterprise server that would "strip" commits from the PRs. They put PRs into this weird state where the comments are still there, but "Commits" and "Files changes" tabs no longer work.
- At the same time, one of the team members discovered that by searching for `startRepositoryMigration`, one can find repos like https://github.com/tspascoal/gei-basic-scripts which allows one to inspect intermediate migration files exported by source repo, and modify them before continuing migration and importing to destination repo
   - There are two of files per migrated repository: an archive with regular git repo, and archive full of json files which describes issues, PRs and so on
   - With some creative python and somewhat fragile manual steps, we were able to `git-filter-repo` first archive, and then rewrite references in 2nd archive to point to new commits. Sorry, this script is very raw and hard to use, and I don't think it can be shared with others.
   - This worked, and we've got all the PRs with updated refs.. but this was quite a journey! Taking an official road and dereferencing every PR would be an easier solution, even if it would have some data loss..
