### ISSUE TITLE
Better logging information

### ISSUE THREAD

**Issue by admiralAwkbar** [github/gh-gei#446] opened 2022-06-14 18:21 UTC
## Description

Hey All!

I have been running a lot of migrations and adding the `REPO_NAME` in the output would make hunting failures and success much easier...

### Current Output

```
[11:35 AM] [INFO] Migration RM_kgDaACQ1MjgxNjE5ZS0yYTg4LTQ2YWQtODg0Mi1hMTJmNGI5NjJiNTU is IN_PROGRESS
[11:35 AM] [INFO] Waiting 10 seconds...
[11:35 AM] [INFO] Migration succeeded for migration RM_kgDaACQ1MjgxNjE5ZS0yYTg4LTQ2YWQtODg0Mi1hMTJmNGI5NjJiNTU
[11:35 AM] [INFO] You are running the latest version of the gei CLI [v0.18]
[11:35 AM] [INFO] Waiting for migration RM_kgDaACQwM2Q3ZTZkZS1hOTUyLTQwNDMtOWU3NC0zMDQ4NmFkYmMxZTE to finish...
[11:35 AM] [ERROR] Migration failed for migration RM_kgDaACQwM2Q3ZTZkZS1hOTUyLTQwNDMtOWU3NC0zMDQ4NmFkYmMxZTE
[11:35 AM] [ERROR] Git source migration failed. Error message: the server responded with status 422
```

### Proposed output
```
[11:35 AM] [INFO] Migration RM_kgDaACQ1MjgxNjE5ZS0yYTg4LTQ2YWQtODg0Mi1hMTJmNGI5NjJiNTU is IN_PROGRESS
[11:35 AM] [INFO] Waiting 10 seconds...
[11:35 AM] [INFO] Migration succeeded for migration RM_kgDaACQ1MjgxNjE5ZS0yYTg4LTQ2YWQtODg0Mi1hMTJmNGI5NjJiNTU, REPO_NAME:[repo1]
[11:35 AM] [INFO] You are running the latest version of the gei CLI [v0.18]
[11:35 AM] [INFO] Waiting for migration RM_kgDaACQwM2Q3ZTZkZS1hOTUyLTQwNDMtOWU3NC0zMDQ4NmFkYmMxZTE to finish...
[11:35 AM] [ERROR] Migration failed for migration RM_kgDaACQwM2Q3ZTZkZS1hOTUyLTQwNDMtOWU3NC0zMDQ4NmFkYmMxZTE, REPO_NAME:[repo2]
[11:35 AM] [ERROR] Git source migration failed. Error message: the server responded with status 422
```

### Conclusion
When running for many repos, it's a bit hard to visually parse the repo that may have failed.
Of course you can grep the logs and find the specific repo, but could be an easy feature to add additional visibilty

**Comment by dylan-smith** [comment] 2022-06-14 20:11
Boy, are you ever in luck! We implemented that already last week, it's already in main, just waiting for the next release of the CLI.

duplicate of: https://github.com/github/gh-gei/issues/368

**Closed** 2022-06-22 02:42 UTC
