### ISSUE TITLE
GHES HA Replication Failure 

### ISSUE THREAD

**Issue by kyle-jones** [github/gh-gei#672] opened 2022-10-07 13:56 UTC
## Description
The following issue is documented in support ticket 1782205
We are running GHES v3.4.9 with the HA replication. When we use the GEI CLI to migrate it breaks the alambic object replication.

## Reproduction Steps
In our QA environment we can setup up a functional HA replication system. But when we issue a "gh gei migrate-repo" command migrating from the local GHES to the Enterprise user cloud version the alambic object replication is stopped and every migration adds to the object backlog. All efforts to teardown and re setup have not resolved the issue.

**Comment by dylan-smith** [comment] 2022-10-19 21:34
I'm going to close this issue because the root cause here is not a bug with the CLI, but with how GHES generates migration archives. We are tracking this separately with the support ticket, and other backlog items in different repos.

**Closed by dylan-smith** 2022-10-19 21:34 UTC
Labels: bug
