### ISSUE TITLE
better efficiency when repos exist in destination

### ISSUE THREAD

**Issue by robandpdx** [github/gh-gei#680] opened 2022-10-13 16:35 UTC
## Description
This feedback came from a customer migration many repos in an org from GHES to GHEC using the generated migration script.

The repo migration should check to see if the destination repo exists before it generates a migration archive and transfers it to the azure storage account.  It would make the repo migration fail faster and allow the script to run quicker when some repos already exist in the destination org.

The customer restarted the migration script because of previous errors and it only needed one repository to be transferred, but had to wait for it to fail on all of the other repositories. The script was started at 11:11 and ended at 11:42.

**Comment by testworksau** [comment] 2022-10-19 02:33
Is this related to / the same as the issue below?

https://github.com/github/gh-gei/issues/626

**Comment by dylan-smith** [comment] 2022-10-19 21:46
thanks for the feedback @robandpdx . Like @testworksau suggested, I think this is a duplicate of another issue in our backlog so I'm going to close this in favor of #626

**Closed by dylan-smith** 2022-10-19 21:46 UTC
