### ISSUE TITLE
Allow migration from Github Enterprise Server without using S3/Azure

### ISSUE THREAD

**Issue by lukens** [github/gh-gei#827] opened 2023-02-20 16:45 UTC
## Description

Currently a migration from Github Enterprise Server requires the use of S3 or Azure buckets for passing the archive.

The rationale for this is that many Enterprise Server instances are not publicly accessible.

However, some (many?) _are_ publicly accessible, and so this requirement adds an additional unnecessary step (and potential point of failure) to the migration.

I suggest the addition of a parameter to allow direct migration from a publicly accessible GitHub Enterprise server cloud instance.

Personally, I ended up using the migration APIs directly, but I feel this enhancement would benefit others.

**Comment by timrogers** [comment] 2023-02-20 17:19
@lukens Thanks for this feedback! We really appreciate it. I definitely agree that it would be good to explicitly support this scenario in the CLI.

**Comment by dylan-smith** [comment] 2023-03-28 17:39
With GHES 3.8+ I don't think this feature is even possible to support anymore. Because generation of the migration archive now requires S3/Azure to be configured in GHES itself.

Do you agree @timrogers ? if so we should close this issue IMO.

**Comment by dylan-smith** [comment] 2023-03-29 04:47
Duplicate of #751

**Closed by dylan-smith** 2023-03-29 04:47 UTC
